naming:
  FunctionNaming:
    functionPattern: '[a-z][a-zA-Z0-9]*'
  TopLevelPropertyNaming:
    constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
  LongParameterList:
    functionThreshold: 7
    constructorThreshold: 7
    ignoreDefaultParameters: true
    ignoreAnnotated: [ 'Serializable' ]
    
formatting:
  TrailingCommaOnCallSite:
    active: true
  TrailingCommaOnDeclarationSite:
    active: true
    
style:
  AlsoCouldBeApply:
    active: true
  BracesOnIfStatements:
    active: true
    singleLine: 'never'
    multiLine: 'always'